---
- name: Create Rancher cluster via API
  hosts: localhost
  gather_facts: false
  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"

  tasks:
    - name: Create OpenStack cluster in Rancher
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          metadata:
            name: "openstack-cluster"
            namespace: "fleet-default"
          spec:
            kubernetesVersion: "v1.33.4+rke2r1"
            cloudCredentialSecretName: "cattle-global-data:cc-abcde"  # Your cloud credential
            rkeConfig:
              machinePools:
                - name: "all-in-one"
                  quantity: 1
                  etcdRole: true
                  controlPlaneRole: true
                  workerRole: true
                  machineConfigRef:
                    kind: "VmwarevsphereMachineConfig"  # Use a supported kind or remove
                    name: "default-config"
        validate_certs: false
      register: create_cluster_response

    - name: Show response from Rancher API
      debug:
        var: create_cluster_response.json
