- name: Create True Rancher Custom Cluster (Imported Cluster)
  hosts: localhost
  gather_facts: false

  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "custom-cluster"
    kubernetes_version: "v1.33.1+rke2r1"

  tasks:
    - name: Display survey inputs
      debug:
        msg:
          - "Creating TRUE custom cluster: {{ cluster_name }}"
          - "Node Count: {{ node_count }}"
          - "Node Roles: {{ node_roles }}"

    - name: Fix node_roles format
      set_fact:
        actual_node_roles: "{{ (node_roles | first).split(',') if node_roles is iterable and node_roles | first is string and ',' in node_roles | first else node_roles }}"

    - name: Validate configuration
      assert:
        that:
          - node_count | int >= 1
          - node_count | int <= 20
          - ("etcd" in actual_node_roles and node_count | int >= 3) or "etcd" not in actual_node_roles
        fail_msg: |
          Invalid configuration:
          - Need minimum 3 nodes if etcd role is selected
        success_msg: "Configuration validated"

    - name: Create custom cluster using v3 API (NOT provisioning API)
      uri:
        url: "{{ rancher_url }}/v3/clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ cluster_name }}"
          type: "cluster"
          labels: {}
          annotations: {}
        validate_certs: false
        status_code: 201
      register: create_cluster_response

    - name: Display cluster creation response
      debug:
        var: create_cluster_response.json

    - name: Wait for cluster to be created
      uri:
        url: "{{ rancher_url }}/v3/clusters/{{ create_cluster_response.json.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: false
        status_code: 200
      register: cluster_info
      until: cluster_info.json.state == "active"
      retries: 30
      delay: 5

    - name: Get node registration command for CUSTOM cluster
      uri:
        url: "{{ rancher_url }}/v3/clusters/{{ create_cluster_response.json.id }}/clusterregistrationtokens"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "clusterRegistrationToken"
          clusterId: "{{ create_cluster_response.json.id }}"
        validate_certs: false
        status_code: 201
      register: token_response

    - name: Wait for token to be ready
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens/{{ token_response.json.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: false
        status_code: 200
      register: final_token
      until: final_token.json.nodeCommand is defined
      retries: 10
      delay: 3

    - name: Display TRUE CUSTOM CLUSTER registration command
      debug:
        msg:
          - "✅ TRUE CUSTOM CLUSTER CREATED SUCCESSFULLY!"
          - "Cluster Name: {{ cluster_name }}"
          - "Cluster ID: {{ create_cluster_response.json.id }}"
          - "Cluster Type: {{ create_cluster_response.json.type }}"
          - "Total Nodes to Register: {{ node_count }}"
          - "Roles for Each Node: {{ actual_node_roles }}"
          - ""
          - "📋 CUSTOM CLUSTER REGISTRATION COMMAND (RKE/K3s):"
          - "{{ final_token.json.nodeCommand }}"
          - ""
          - "🔧 MANUAL KUBERNETES INSTALLATION REQUIRED:"
          - "1. Install Kubernetes (RKE2/K3s) manually on {{ node_count }} nodes"
          - "2. THEN run the registration command above on each node"
          - "3. This is a TRUE custom cluster - you manage Kubernetes installation"
          - "4. Nodes should have roles: {{ actual_node_roles }}"

    - name: Save custom cluster registration info
      copy:
        content: |
          TRUE CUSTOM CLUSTER Registration Information
          ============================================
          Cluster Name: {{ cluster_name }}
          Cluster ID: {{ create_cluster_response.json.id }}
          Cluster Type: Imported Custom Cluster
          Node Count: {{ node_count }}
          Node Roles: {{ actual_node_roles }}
          
          IMPORTANT: This is a CUSTOM cluster where YOU install Kubernetes.
          
          Steps:
          1. Install RKE2 or K3s manually on {{ node_count }} nodes
          2. Configure nodes with roles: {{ actual_node_roles }}
          3. Run this registration command on each node:
          
          {{ final_token.json.nodeCommand }}
          
          4. Nodes will appear as 'Imported' in Rancher
        dest: "/tmp/{{ cluster_name }}-custom-cluster-registration.txt"
      delegate_to: localhost
