---
- name: Create Rancher Custom Cluster via API
  hosts: localhost
  gather_facts: false

  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "openstack-cluster"
    kubernetes_version: "v1.33.1+rke2r1"   # You may adjust based on Rancher availability

  tasks:
    - name: Ensure node_roles is a list (in case survey sends string)
      set_fact:
        node_roles_list: >-
          {{ (node_roles if node_roles is sequence else (node_roles|string).split(',')) | map('trim') | list }}

    - name: Create OpenStack cluster in Rancher (Custom Cluster)
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          apiVersion: provisioning.cattle.io/v1
          kind: Cluster
          metadata:
            name: "{{ cluster_name }}"
            namespace: fleet-default
          spec:
            kubernetesVersion: "{{ kubernetes_version }}"
            rkeConfig:
              machinePools:
                - name: "{{ pool_name }}"
                  quantity: "{{ node_count | int }}"
                  roles: "{{ node_roles_list }}"
                  displayName: "{{ pool_name }}"
                  hostnamePrefix: "{{ cluster_name }}-node"
                  machineConfigRef:
                    kind: MachineConfig
                    name: "{{ pool_name }}"
              chartValues:
                rke2-coredns: {}
                rke2-ingress-nginx: {}
                rke2-kube-proxy: {}
                rke2-metrics-server: {}
        validate_certs: false
        status_code: 201
      register: create_cluster_response

    - name: Show Rancher API response
      debug:
        var: create_cluster_response.json
