---
- name: Create Rancher cluster via API
  hosts: localhost
  gather_facts: false
  vars:
    rancher_url: "https://192.168.210.32/"
    api_token: "token-kt4rg:zppllkvsr7xl5cndlb4n4njqbckzjsmkd557xbgmh69bzdc7kqrkbl"

  tasks:
    - name: Create OpenStack cluster in Rancher
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          metadata:
            name: "{{ cluster_name }}"
            namespace: "fleet-default"
          spec:
            kubernetesVersion: "v1.34.1+rke2r1"
            rkeConfig:
              machinePools: []
        validate_certs: false
        status_code: 201
      register: create_cluster_response

    - name: Show response from Rancher API
      debug:
        var: create_cluster_response.json
