---
- name: Create Custom Provider Cluster in Rancher
  hosts: localhost
  gather_facts: no
  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "openstack-cluster"

  tasks:
    - name: Create cluster payload
      set_fact:
        cluster_payload:
          type: cluster
          name: "{{ cluster_name }}"
          customClusterConfig:
            rancherKubernetesEngineConfig:
              # You can define more config here as needed
              machinePools:
                - name: "{{ pool_name }}"
                  nodeCount: "{{ node_count | int }}"
                  roles: "{{ node_roles.split(',') }}"
                  # Other fields like 'machineConfig' or 'labels' can be added if needed

    - name: Create Rancher cluster
      uri:
        url: "{{ rancher_url }}/v3/clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body: "{{ cluster_payload | to_json }}"
        status_code: 201
        return_content: yes
      register: rancher_cluster_response

    - name: Show Rancher cluster creation response
      debug:
        var: rancher_cluster_response.json
