---
- name: Create OpenStack VMs and make Rancher cluster ACTIVE
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ############################
    # RANCHER
    ############################
    rancher_url: "https://192.168.210.32"
    rancher_token: "token-REPLACE_ME"
    cluster_name: "{{ cluster_name }}"

    ############################
    # AWX SURVEY VARIABLES
    ############################
    vm_count: "{{ vm_count | int }}"
    vm_name_prefix: "{{ vm_name_prefix }}"
    node_roles: "{{ node_roles }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"

    ############################
    # VM STATIC DETAILS
    ############################
    vm_image: "4e04bf46-b48f-4bd2-a15a-efdd3a666d43"
    vm_keypair: "k8s"

    ############################
    # OPENSTACK AUTH (FROM OPENRC)
    ############################
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_user_domain_name: "Default"
    os_username: "admin"
    os_password: "stackmax"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:

       ###########################################################################
    # VALIDATION
    ###########################################################################

    - name: Validate vm_count
      fail:
        msg: "vm_count must be positive"
      when: vm_count < 1

    - name: Convert comma-separated roles into list
      set_fact:
        parsed_roles: "{{ node_roles.split(',') }}"

    - name: Ensure role count matches VM count
      assert:
        that:
          - parsed_roles | length == vm_count
        fail_msg: "Number of roles does not match number of VMs!"

    - name: Ensure VM names count matches vm_count
      assert:
        that:
          - vm_names_list | length == vm_count
        fail_msg: "VM name count does not match vm_count!"

    - name: Build VM → role map
      set_fact:
        vm_role_map: "{{ vm_names_list | zip(parsed_roles) | list }}"

    - name: Show VM role mapping
      debug:
        msg: "VM {{ item.0 }} will be {{ item.1 }}"
      loop: "{{ vm_role_map }}"


    ###########################################################################
    # RANCHER API CALLS
    ###########################################################################

    - name: Get Rancher cluster info
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_info

    - name: Fail if cluster not found
      fail:
        msg: "Cluster {{ cluster_name }} not found in Rancher!"
      when: cluster_info.json.data | length == 0

    - name: Set Rancher cluster ID
      set_fact:
        cluster_id: "{{ cluster_info.json.data[0].id }}"

    - name: Show Rancher cluster ID
      debug:
        msg: "Cluster ID: {{ cluster_id }}"

    - name: Check for existing registration tokens
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: existing_tokens

    - name: Create Rancher registration token if needed
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
        status_code: [200, 201]
      register: token_create
      when: existing_tokens.json.data | length == 0
      ignore_errors: yes

    - name: Wait for nodeCommand to be ready
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: reg_info
      until: reg_info.json.data[0].nodeCommand is defined and reg_info.json.data[0].nodeCommand != ""
      retries: 20
      delay: 5

    - name: Store node command and token
      set_fact:
        node_command: "{{ reg_info.json.data[0].nodeCommand }}"
        registration_token: "{{ reg_info.json.data[0].token }}"

    - name: Confirm node command fetched
      debug:
        msg: "Node command obtained successfully (token: {{ registration_token[:10] }}...)"


    ###########################################################################
    # CLOUD-INIT GENERATION
    ###########################################################################

    - name: Create cloud-init files
      copy:
        dest: "/tmp/cloud-init-{{ item.0 }}.yml"
        content: |
          #cloud-config
          package_update: true
          packages:
            - curl
            - docker.io
            - jq
            - iptables
            - conntrack
            - nfs-common
            - apparmor-utils

          write_files:
            - path: /etc/hosts
              content: |
                10.1.77.17 k8smanager.comtegra.pl
              owner: root:root
              permissions: '0644'

          runcmd:
            - echo "=== Starting Node Registration for {{ item.0 }} as {{ item.1 }} ==="
            - systemctl enable docker
            - systemctl start docker
            - usermod -aG docker ubuntu
            - sleep 10
            - |
              BASE="{{ node_command }}"
              BASE=$(echo "$BASE" | sed 's/curl /curl -k /g')
              FINAL="$BASE"
              {% if 'etcd' in item.1 %}FINAL="$FINAL --etcd"{% endif %}
              {% if 'controlplane' in item.1 %}FINAL="$FINAL --controlplane"{% endif %}
              {% if 'worker' in item.1 %}FINAL="$FINAL --worker"{% endif %}
              FINAL="$FINAL --node-name {{ item.0 }}"
              echo "$FINAL" > /tmp/rancher_join.sh
              chmod +x /tmp/rancher_join.sh
              /tmp/rancher_join.sh
            - echo "=== Node registration completed ==="
            - docker ps
      loop: "{{ vm_role_map }}"


    ###########################################################################
    # CREATE VMS
    ###########################################################################

    - name: Create VM on OpenStack
      openstack.cloud.server:
        state: present
        name: "{{ item.0 }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        userdata: "{{ lookup('file', '/tmp/cloud-init-' + item.0 + '.yml') }}"
        auto_ip: yes
        wait: yes
        timeout: 600
        validate_certs: false
      environment:
        OS_AUTH_URL: "{{ os_auth_url }}"
        OS_PROJECT_NAME: "{{ os_project_name }}"
        OS_PROJECT_ID: "{{ os_project_id }}"
        OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
        OS_USERNAME: "{{ os_username }}"
        OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
        OS_PASSWORD: "{{ os_password }}"
        OS_REGION_NAME: "{{ os_region_name }}"
        OS_INTERFACE: "{{ os_interface }}"
        OS_IDENTITY_API_VERSION: "{{ os_identity_api_version }}"
      register: new_vms
      loop: "{{ vm_role_map }}"
      ignore_errors: yes


    ###########################################################################
    # DISPLAY VM INFO
    ###########################################################################

    - name: Display VM information
      debug:
        msg: |
          VM {{ item.0 }} created
          Status: {{ new_vms.results[loop.index0].server.status | default('Unknown') }}
          ID: {{ new_vms.results[loop.index0].server.id | default('Unknown') }}
      loop: "{{ vm_role_map }}"
      when: new_vms is defined


    ###########################################################################
    # WAIT FOR CLUSTER ACTIVATION
    ###########################################################################

    - name: Wait for nodes to register in Rancher
      uri:
        url: "{{ rancher_url }}/v3/nodes?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: rancher_nodes
      until: rancher_nodes.json.data | length >= vm_count
      retries: 500
      delay: 10
      ignore_errors: yes

    - name: Show registered nodes count
      debug:
        msg: "Found {{ rancher_nodes.json.data | length }} nodes in Rancher"

    - name: Wait for cluster to become active
      uri:
        url: "{{ rancher_url }}/v3/clusters/{{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_state
      until:
        - cluster_state.json.state == "active"
        - cluster_state.json.conditions
          | selectattr('type', 'equalto', 'Ready')
          | map(attribute='status')
          | first == "True"
      retries: 600
      delay: 10

    - name: Show final cluster status
      debug:
        msg: |
          ✅ CLUSTER ACTIVE!
          Cluster: {{ cluster_name }}
          State: {{ cluster_state.json.state }}
          Kubernetes Version: {{ cluster_state.json.version.gitVersion | default('N/A') }}


    ###########################################################################
    # CLEANUP
    ###########################################################################

    - name: Remove cloud-init temp files
      file:
        path: "/tmp/cloud-init-{{ item.0 }}.yml"
        state: absent
      loop: "{{ vm_role_map }}"

    - name: Final success message
      debug:
        msg: |
          🎉 SUCCESS!
          Cluster {{ cluster_name }} is now fully operational.
          Created VMs: {{ vm_names_list | join(', ') }}
