---
- name: Create VM on OpenStack and auto-register to Rancher (Simplified)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # Rancher details
    rancher_url: "https://192.168.170.67"
    rancher_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "openstack-cluster"

    # OpenStack details
    vm_name: "rancher-node-1"
    vm_image: "7e19db1a-48d4-4418-b5e2-d2a5dc611a69"
    vm_flavor: "6a7bab60-adc2-4cff-8db7-6a4f1f866ac2"
    vm_keypair: "rke"
    vm_net: "bce77acb-b609-4205-a00a-6964072d4068"

  tasks:
    - name: Get cluster ID from Rancher
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
          Content-Type: "application/json"
        validate_certs: no
      register: cluster_info

    - name: Extract cluster ID
      set_fact:
        cluster_id: "{{ cluster_info.json.data[0].id }}"

    - name: Get registration token from Rancher
      uri:
        url: "{{ rancher_url }}/v3/clusterregistrationtokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
          Content-Type: "application/json"
        validate_certs: no
      register: reg_info

    - name: Use the insecureNodeCommand directly from Rancher and add roles
      set_fact:
        registration_command: "{{ reg_info.json.data[0].insecureNodeCommand }} --etcd --controlplane --worker --label 'cattle.io/os=linux'"

    - name: Create cloud-init user_data file
      copy:
        dest: ./cloud-init-{{ vm_name }}.yml
        content: |
          #cloud-config
          package_update: true
          packages:
            - curl
          runcmd:
            - curl -fsSL https://get.docker.com | sh
            - usermod -aG docker ubuntu
            - {{ registration_command }}

    - name: Create VM on OpenStack with cloud-init
      os_server:
        state: present
        name: "{{ vm_name }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        nics:
          - net-id: "{{ vm_net }}"
        userdata: "{{ lookup('file', './cloud-init-' + vm_name + '.yml') }}"
        auto_ip: yes
        cloud:
          auth:
            auth_url: "http://192.168.150.31:5000/v3"
            project_name: "XAS"
            project_domain_name: "Default"
            username: "admin"
            user_domain_name: "Default"
            password: "2rlpcV3k3OPv"
          region_name: "RegionOne"
      register: new_vm

    - debug:
        msg: "VM {{ vm_name }} created with IP {{ new_vm.server.public_v4 | default(new_vm.server.private_v4) | default('No IP assigned') }}"
