---
- name: Create multiple VMs on OpenStack and auto-register to Rancher (RKE2)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    rancher_url: "https://192.168.210.32"
    rancher_token: "token-kt4rg:zppllkvsr7xl5cndlb4n4njqbckzjsmkd557xbgmh69bzdc7kqrkbl"
    cluster_name: "{{ cluster_name }}"

    vm_count: "{{ vm_count | int }}"
    node_roles: "{{ node_roles }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"
    vm_names_list: "{{ vm_name_prefix.split(',') }}"

    vm_image: "494c4e8c-d11b-43b7-9e8b-df4009b7102b"
    vm_keypair: "k8s"

    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:

    ###########################################################################
    # ROLE NORMALIZATION
    ###########################################################################
    - set_fact:
        parsed_roles: >-
          {{
            [node_roles]
            if vm_count == 1
            else (node_roles.split(',') | map('trim') | list)
          }}

    - set_fact:
        vm_role_map: "{{ vm_names_list | zip(parsed_roles) | list }}"

    ###########################################################################
    # RANCHER API
    ###########################################################################
    - name: Get Rancher cluster
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_info

    - set_fact:
        cluster_id: "{{ cluster_info.json.data[0].id }}"

    - name: Get registration token
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
      failed_when: false

    - name: Fetch nodeCommand
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: reg_info
      until: reg_info.json.data[0].nodeCommand is defined
      retries: 20
      delay: 5

    - set_fact:
        node_command: "{{ reg_info.json.data[0].nodeCommand }}"

    ###########################################################################
    # CLOUD INIT — RKE2 JOIN
    ###########################################################################
    - name: Create cloud-init files
      copy:
        dest: "/tmp/cloud-init-{{ item.0 }}.yml"
        content: |
          #cloud-config
          package_update: true
          packages:
            - curl

          runcmd:
            - |
              echo "Installing RKE2..."
              {{ node_command | replace('curl ', 'curl -k ') }}

      loop: "{{ vm_role_map }}"

    ###########################################################################
    # CREATE VM
    ###########################################################################
    - name: Create VM on OpenStack
      openstack.cloud.server:
        state: present
        name: "{{ item.0 }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        userdata: "{{ lookup('file', '/tmp/cloud-init-' + item.0 + '.yml') }}"
        auto_ip: no
        wait: no
      environment:
        OS_AUTH_URL: "{{ os_auth_url }}"
        OS_PROJECT_NAME: "{{ os_project_name }}"
        OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
        OS_USERNAME: "{{ os_username }}"
        OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
        OS_PASSWORD: "{{ os_password }}"
        OS_REGION_NAME: "{{ os_region_name }}"
        OS_INTERFACE: "{{ os_interface }}"
        OS_IDENTITY_API_VERSION: "{{ os_identity_api_version }}"
      loop: "{{ vm_role_map }}"

    ###########################################################################
    # WAIT FOR CLUSTER ACTIVE
    ###########################################################################
    - name: Wait for cluster to become active
      uri:
        url: "{{ rancher_url }}/v3/clusters/{{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_state
      until: cluster_state.json.state == "active"
      retries: 600
      delay: 10

    - debug:
        msg: "✅ Cluster {{ cluster_name }} is ACTIVE"
