- name: Create Rancher Custom Cluster
  hosts: localhost
  gather_facts: false

  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "custom-cluster"
    kubernetes_version: "v1.33.1+rke2r1"

  tasks:
    - name: Display survey inputs
      debug:
        msg:
          - "Survey Variables Received:"
          - "node_count: {{ node_count }}"
          - "node_roles: {{ node_roles }}"
          - "Type of node_roles: {{ node_roles | type }}"

    - name: Validate node_roles is a list
      assert:
        that:
          - node_roles is iterable
        fail_msg: "node_roles must be a list. Check AWX survey configuration."
        success_msg: "node_roles is a valid list"

    - name: Validate configuration
      assert:
        that:
          - node_count | int >= 1
          - node_count | int <= 20
          - ("etcd" in node_roles and node_count | int >= 3) or "etcd" not in node_roles
        fail_msg: |
          Invalid configuration:
          - node_count must be between 1-20
          - If etcd role is selected, need minimum 3 nodes for HA
        success_msg: "Configuration validated successfully"

    - name: Create cluster
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        # ... rest of cluster creation code
