- name: Create True Custom Cluster (Manual Kubernetes Installation)
  hosts: localhost
  gather_facts: false

  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "custom-cluster"
    kubernetes_version: "v1.33.1+rke2r1"

  tasks:
    - name: Display survey inputs
      debug:
        msg:
          - "Creating TRUE custom cluster: {{ cluster_name }}"
          - "Node Count: {{ node_count }}"
          - "Node Roles: {{ node_roles }}"

    - name: Fix node_roles format
      set_fact:
        actual_node_roles: "{{ (node_roles | first).split(',') if node_roles is iterable and node_roles | first is string and ',' in node_roles | first else node_roles }}"

    - name: Validate configuration
      assert:
        that:
          - node_count | int >= 1
          - node_count | int <= 20
          - ("etcd" in actual_node_roles and node_count | int >= 3) or "etcd" not in actual_node_roles
        fail_msg: |
          Invalid configuration:
          - Need minimum 3 nodes if etcd role is selected
        success_msg: "Configuration validated"

    - name: Create custom cluster with explicit driver
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          apiVersion: provisioning.cattle.io/v1
          kind: Cluster
          metadata:
            name: "{{ cluster_name }}"
            namespace: fleet-default
          spec:
            kubernetesVersion: "{{ kubernetes_version }}"
            rkeConfig: 
              machinePools: []
            # Explicitly set to empty driver for custom cluster
        validate_certs: false
        status_code: 201
      register: create_cluster_response

    - name: Wait for cluster to be ready
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters/fleet-default/{{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: false
        status_code: 200
      register: cluster_status
      until: cluster_status.json.state == "provisioning"
      retries: 30
      delay: 5

    - name: Get cluster registration token for CUSTOM workflow
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          clusterId: "{{ cluster_name }}"
        validate_certs: false
        status_code: 201
      register: token_response

    - name: Wait for token to be ready
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens/{{ token_response.json.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
        validate_certs: false
        status_code: 200
      register: final_token
      until: final_token.json.nodeCommand is defined
      retries: 10
      delay: 3

    - name: Display MANUAL INSTALLATION instructions
      debug:
        msg:
          - "✅ CUSTOM CLUSTER FRAMEWORK CREATED SUCCESSFULLY!"
          - "Cluster Name: {{ cluster_name }}"
          - "Cluster Type: Manual Kubernetes Installation Required"
          - ""
          - "🚨 MANUAL KUBERNETES INSTALLATION REQUIRED:"
          - "==========================================="
          - "This is a TRUE custom cluster. You must manually install Kubernetes."
          - ""
          - "Step 1: INSTALL KUBERNETES on {{ node_count }} nodes:"
          - "----------------------------------------------------"
          - "Choose ONE of these methods:"
          - ""
          - "OPTION A: Install RKE2 manually:"
          - "  curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION='{{ kubernetes_version }}' sh -"
          - "  # Configure roles in /etc/rancher/rke2/config.yaml"
          - ""
          - "OPTION B: Install K3s manually:"
          - "  curl -sfL https://get.k3s.io | sh -"
          - ""
          - "Step 2: CONFIGURE NODE ROLES:"
          - "---------------------------"
          - "Ensure nodes have these roles: {{ actual_node_roles }}"
          - "- etcd: Store cluster data"
          - "- controlplane: Kubernetes API server"
          - "- worker: Run workloads"
          - ""
          - "Step 3: REGISTER NODES WITH RANCHER:"
          - "-----------------------------------"
          - "Run this command on EACH node AFTER Kubernetes is installed:"
          - "{{ final_token.json.nodeCommand }}"
          - ""
          - "Step 4: WAIT FOR REGISTRATION:"
          - "----------------------------"
          - "Monitor in Rancher UI until all {{ node_count }} nodes appear"

    - name: Save MANUAL installation instructions
      copy:
        content: |
          TRUE CUSTOM CLUSTER - MANUAL INSTALLATION
          ========================================
          
          Cluster Name: {{ cluster_name }}
          Kubernetes Version: {{ kubernetes_version }}
          Node Count: {{ node_count }}
          Node Roles: {{ actual_node_roles }}
          
          IMPORTANT: This cluster requires MANUAL Kubernetes installation.
          
          STEP 1: INSTALL KUBERNETES ON NODES
          -----------------------------------
          Install RKE2 or K3s manually on each node:
          
          For RKE2:
          curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION='{{ kubernetes_version }}' sh -
          
          For K3s:
          curl -sfL https://get.k3s.io | sh -
          
          STEP 2: CONFIGURE NODE ROLES
          ----------------------------
          Configure each node with appropriate roles in Kubernetes configuration.
          
          STEP 3: REGISTER WITH RANCHER
          -----------------------------
          Run this command on each node AFTER Kubernetes is running:
          
          {{ final_token.json.nodeCommand }}
          
          STEP 4: VERIFY
          --------------
          Check Rancher UI to see all {{ node_count }} nodes registered.
          
          Expected node roles: {{ actual_node_roles }}
        dest: "/tmp/{{ cluster_name }}-manual-installation.txt"
      delegate_to: localhost
