---
- name: Create Rancher Custom Provider Cluster
  hosts: localhost
  gather_facts: no

  vars:
    # Rancher connection details
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"

    # Hardcoded cluster name
    cluster_name: "openstack-cluster"

    # These still come from AWX survey or CLI
    node_roles: "{{ node_roles }}"             # e.g. "etcd,controlplane,worker"
    node_count: "{{ node_count | int }}"       # e.g. 3
    pool_name: "{{ pool_name }}"               # e.g. "default-pool"

  tasks:
    - name: Prepare cluster payload
      set_fact:
        cluster_payload:
          type: cluster
          name: "{{ cluster_name }}"
          customClusterConfig:
            rancherKubernetesEngineConfig:
              machinePools:
                - name: "{{ pool_name }}"
                  nodeCount: "{{ node_count }}"
                  roles: "{{ node_roles.split(',') }}"

    - name: Create cluster in Rancher
      uri:
        url: "{{ rancher_url }}/v3/clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body: "{{ cluster_payload | to_json }}"
        body_format: json
        validate_certs: no
        status_code: [201, 409]  # 409 = cluster already exists
      register: result

    - name: Show result
      debug:
        var: result.json
