- name: Create Rancher Custom Provider Cluster
  hosts: localhost
  gather_facts: no
  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "openstack-cluster"
  tasks:
    - name: Prepare cluster payload
      set_fact:
        cluster_payload:
          type: cluster
          name: "{{ cluster_name }}"
          customClusterConfig:
            rancherKubernetesEngineConfig:
              machinePools:
                - name: "{{ pool_name }}"
                  nodeCount: "{{ node_count | int }}"
                  roles: "{{ node_roles.split(',') }}"
                  
    - name: Create cluster in Rancher
      uri:
        url: "{{ rancher_url }}/v3/clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body: "{{ cluster_payload | to_json }}"
        status_code: 201
        return_content: yes
      register: result

    - name: Show result
      debug:
        var: result.json
