---
- name: Create Rancher Custom Cluster via API (Provisioning v1)
  hosts: localhost
  gather_facts: false

  vars:
    # Hardcoded or template-level vars
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "openstack-cluster"
    kubernetes_version: "v1.33.1+rke2r1"   # Adjust if needed

  tasks:
    - name: Validate node_roles is a list
      assert:
        that:
          - node_roles is iterable
        fail_msg: "node_roles must be a list (use 'Multiple Choice' in AWX survey)."
        success_msg: "node_roles is a valid list."

    - name: Create OpenStack cluster in Rancher (Custom Cluster)
      uri:
        url: "{{ rancher_url }}/v1/provisioning.cattle.io.clusters"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          apiVersion: provisioning.cattle.io/v1
          kind: Cluster
          metadata:
            name: "{{ cluster_name }}"
            namespace: fleet-default
          spec:
            kubernetesVersion: "{{ kubernetes_version }}"
            rkeConfig:
              machinePools:
                - name: "{{ pool_name }}"
                  quantity: "{{ node_count | int }}"
                  roles: "{{ node_roles }}"
                  displayName: "{{ pool_name }}"
                  hostnamePrefix: "{{ cluster_name }}-node"
                  machineConfigRef:
                    kind: MachineConfig
                    name: "{{ pool_name }}"
              chartValues:
                rke2-coredns: {}
                rke2-ingress-nginx: {}
                rke2-kube-proxy: {}
                rke2-metrics-server: {}
        validate_certs: false
        status_code: 201
      register: create_cluster_response

    - name: Show Rancher API response
      debug:
        var: create_cluster_response.json
