---
- name: Create OpenStack VMs and register to existing Rancher custom cluster
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    ###########################################################################
    # RANCHER DETAILS
    ###########################################################################
    rancher_url: "https://192.168.210.32"
    rancher_token: "token-XXXXXXXXXXXXXXXXXXXXXXXX"
    cluster_name: "{{ cluster_name }}"

    ###########################################################################
    # SURVEY INPUTS
    ###########################################################################
    vm_count: "{{ vm_count | int }}"
    node_roles: "{{ node_roles }}"
    vm_name_prefix: "{{ vm_name_prefix }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"   # NAME or ID (both supported)

    ###########################################################################
    # VM DETAILS
    ###########################################################################
    vm_image: "a997754d-6cdf-4a21-8e52-5df389d3f7c5"
    vm_keypair: "k8s"

    ###########################################################################
    # OPENSTACK AUTH
    ###########################################################################
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "********"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:
  ###########################################################################
  # INPUT NORMALIZATION
  ###########################################################################
  - name: Generate VM names
    set_fact:
      vm_names_list: >-
        {{ range(1, vm_count + 1)
           | map('string')
           | map('regex_replace', '^(.*)$', vm_name_prefix ~ '\\1')
           | list }}

  - name: Normalize node roles
    set_fact:
      parsed_roles: "{{ node_roles.split(',') | map('trim') | list }}"

  - name: Validate inputs
    assert:
      that:
        - vm_names_list | length == vm_count
        - parsed_roles | length == vm_count
      fail_msg: >
        VM count, VM names, and roles must match.
        vm_count={{ vm_count }},
        names={{ vm_names_list }},
        roles={{ parsed_roles }}

  - name: Build VM → role map
    set_fact:
      vm_role_map: "{{ vm_names_list | zip(parsed_roles) | list }}"

  ###########################################################################
  # GET RANCHER CLUSTER
  ###########################################################################
  - name: Get Rancher cluster
    uri:
      url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: cluster_info

  - name: Fail if cluster not found
    fail:
      msg: "Cluster {{ cluster_name }} not found in Rancher"
    when: cluster_info.json.data | length == 0

  - set_fact:
      cluster_id: "{{ cluster_info.json.data[0].id }}"

  ###########################################################################
  # GET REGISTRATION COMMAND
  ###########################################################################
  - name: Ensure registration token exists
    uri:
      url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
      method: POST
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      body_format: json
      body:
        clusterId: "{{ cluster_id }}"
      validate_certs: no
    failed_when: false

  - name: Fetch registration command
    uri:
      url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: reg_info
    until: reg_info.json.data[0].nodeCommand is defined
    retries: 20
    delay: 5

  - set_fact:
      node_command: "{{ reg_info.json.data[0].nodeCommand | replace('curl ', 'curl -k ') }}"

  ###########################################################################
  # CLOUD-INIT
  ###########################################################################
  - name: Create cloud-init files
    copy:
      dest: "/tmp/cloud-init-{{ item.0 }}.yml"
      content: |
        #cloud-config
        package_update: true
        packages:
          - curl
          - docker.io
          - nfs-common

        runcmd:
          - systemctl enable docker
          - systemctl start docker
          - swapoff -a
          - sed -i '/swap/d' /etc/fstab
          - sleep 10
          - |
            CMD='{{ node_command }}'
            {% if 'etcd' in item.1 %}CMD="$CMD --etcd"{% endif %}
            {% if 'controlplane' in item.1 %}CMD="$CMD --controlplane"{% endif %}
            {% if 'worker' in item.1 %}CMD="$CMD --worker"{% endif %}
            CMD="$CMD --node-name {{ item.0 }}"
            echo "$CMD" > /root/join.sh
            chmod +x /root/join.sh
            /root/join.sh
    loop: "{{ vm_role_map }}"

  ###########################################################################
  # CREATE OPENSTACK VMS (FLAVOR NAME OR ID SUPPORTED)
  ###########################################################################
  - name: Create VM on OpenStack
    openstack.cloud.server:
      state: present
      name: "{{ item.0 }}"
      image: "{{ vm_image }}"
      flavor: "{{ vm_flavor }}"   # ✅ NAME OR ID
      key_name: "{{ vm_keypair }}"
      network: "{{ vm_net }}"
      userdata: "{{ lookup('file', '/tmp/cloud-init-' + item.0 + '.yml') }}"
      auto_ip: yes
      wait: yes
      timeout: 600
      config_drive: yes
    environment:
      OS_AUTH_URL: "{{ os_auth_url }}"
      OS_PROJECT_NAME: "{{ os_project_name }}"
      OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
      OS_USERNAME: "{{ os_username }}"
      OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
      OS_PASSWORD: "{{ os_password }}"
      OS_REGION_NAME: "{{ os_region_name }}"
      OS_INTERFACE: "{{ os_interface }}"
      OS_IDENTITY_API_VERSION: "{{ os_identity_api_version }}"
    loop: "{{ vm_role_map }}"
    register: vms

  ###########################################################################
  # WAIT FOR NODES
  ###########################################################################
  - name: Wait for nodes to register
    uri:
      url: "{{ rancher_url }}/v3/nodes?clusterId={{ cluster_id }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: rancher_nodes
    until: rancher_nodes.json.data | length >= vm_count
    retries: 60
    delay: 10

  ###########################################################################
  # WAIT FOR CLUSTER ACTIVE
  ###########################################################################
  - name: Wait for cluster ACTIVE
    uri:
      url: "{{ rancher_url }}/v3/clusters/{{ cluster_id }}"
      method: GET
      headers:
        Authorization: "Bearer {{ rancher_token }}"
      validate_certs: no
    register: cluster_state
    until: cluster_state.json.state == "active"
    retries: 60
    delay: 10

  - name: Success
    debug:
      msg: |
        🎉 CLUSTER ACTIVE
        Name: {{ cluster_name }}
        Nodes: {{ rancher_nodes.json.data | length }}
