---
- name: Create multiple VMs on OpenStack and auto-register to Rancher
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # Rancher details
    rancher_url: "https://192.168.210.32"
    rancher_token: "token-kt4rg:zppllkvsr7xl5cndlb4n4njqbckzjsmkd557xbgmh69bzdc7kqrkbl"
    cluster_name: "{{ cluster_name }}"

    # Survey variables
    vm_count: "{{ vm_count | int }}"
    node_roles: "{{ node_roles }}"
    vm_net: "{{ vm_net }}"
    vm_flavor: "{{ vm_flavor }}"
    vm_names_list: "{{ vm_name_prefix.split(',') }}"

    # VM details
    vm_image: "494c4e8c-d11b-43b7-9e8b-df4009b7102b"
    vm_keypair: "k8s"

    # OpenStack auth
    os_auth_url: "http://192.168.170.50:5000"
    os_project_name: "Production Engineering"
    os_project_domain_id: "default"
    os_username: "admin"
    os_user_domain_name: "Default"
    os_password: "bLEZFvatBShkvUZyKrasUjmNdTTc9c3HcxWykrro"
    os_region_name: "RegionOne"
    os_interface: "public"
    os_identity_api_version: "3"

  tasks:
    ###########################################################################
    # SETUP
    ###########################################################################
    - name: Build VM role mapping
      set_fact:
        parsed_roles: "{{ node_roles.split(',') }}"
        vm_role_map: "{{ vm_names_list | zip(parsed_roles) | list }}"

    ###########################################################################
    # GET RANCHER JOIN COMMAND
    ###########################################################################
    - name: Get cluster ID
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster_info

    - set_fact:
        cluster_id: "{{ cluster_info.json.data[0].id }}"

    - name: Get or create registration token
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
      failed_when: false

    - name: Get node command
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: reg_info
      until: reg_info.json.data[0].nodeCommand != ""
      retries: 10
      delay: 3

    - set_fact:
        node_command: "{{ reg_info.json.data[0].nodeCommand | replace('curl ', 'curl -k ') }}"

    ###########################################################################
    # CREATE VMS WITH PROPER CLOUD-INIT
    ###########################################################################
    - name: Create cloud-init files
      copy:
        dest: "/tmp/cloud-init-{{ item.0 }}.yml"
        content: |
          #cloud-config
          package_update: true
          packages:
            - curl
            - docker.io

          write_files:
            - path: /etc/hostname
              content: "{{ item.0 }}\n"
            - path: /etc/docker/daemon.json
              content: |
                {
                  "exec-opts": ["native.cgroupdriver=systemd"],
                  "storage-driver": "overlay2"
                }

          runcmd:
            # Set hostname (CRITICAL)
            - hostnamectl set-hostname {{ item.0 }}
            
            # Start Docker
            - systemctl enable docker
            - systemctl start docker
            
            # Wait for network
            - sleep 5
            
            # Build join command with role
            - |
              CMD="{{ node_command }}"
              {% if 'etcd' in item.1 %}CMD="$CMD --etcd"{% endif %}
              {% if 'controlplane' in item.1 %}CMD="$CMD --controlplane"{% endif %}
              {% if 'worker' in item.1 %}CMD="$CMD --worker"{% endif %}
              CMD="$CMD --node-name {{ item.0 }}"
              
              # Execute with retry
              for i in 1 2 3; do
                echo "Join attempt $i"
                if bash -c "$CMD"; then
                  echo "Success"
                  break
                fi
                sleep 10
              done
      loop: "{{ vm_role_map }}"

    - name: Create VMs
      openstack.cloud.server:
        state: present
        name: "{{ item.0 }}"
        image: "{{ vm_image }}"
        flavor: "{{ vm_flavor }}"
        key_name: "{{ vm_keypair }}"
        network: "{{ vm_net }}"
        userdata: "{{ lookup('file', '/tmp/cloud-init-' + item.0 + '.yml') }}"
        auto_ip: yes
        wait: yes
        timeout: 300
      environment:
        OS_AUTH_URL: "{{ os_auth_url }}"
        OS_PROJECT_NAME: "{{ os_project_name }}"
        OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
        OS_USERNAME: "{{ os_username }}"
        OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
        OS_PASSWORD: "{{ os_password }}"
        OS_REGION_NAME: "{{ os_region_name }}"
        OS_INTERFACE: "{{ os_interface }}"
        OS_IDENTITY_API_VERSION: "{{ os_identity_api_version }}"
      loop: "{{ vm_role_map }}"
      register: vms

    ###########################################################################
    # WAIT FOR REGISTRATION
    ###########################################################################
    - name: Wait for nodes to register
      uri:
        url: "{{ rancher_url }}/v3/nodes?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: nodes
      until: nodes.json.data | length >= vm_count
      retries: 30
      delay: 10

    - debug:
        msg: "Registered: {{ nodes.json.data | length }}/{{ vm_count }} nodes"

    ###########################################################################
    # WAIT FOR CLUSTER ACTIVE
    ###########################################################################
    - name: Wait for cluster active
      uri:
        url: "{{ rancher_url }}/v3/clusters/{{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ rancher_token }}"
        validate_certs: no
      register: cluster
      until: cluster.json.state == "active"
      retries: 60
      delay: 10

    ###########################################################################
    # CLEANUP & OUTPUT
    ###########################################################################
    - name: Clean temp files
      file:
        path: "/tmp/cloud-init-{{ item }}.yml"
        state: absent
      loop: "{{ vm_names_list }}"

    - debug:
        msg: |
          ✅ Cluster {{ cluster_name }} is ACTIVE
          VMs: {{ vm_names_list | join(', ') }}
          Check: {{ rancher_url }}/c/{{ cluster_id }}
