---
- name: Get Rancher cluster registration command with correct CA checksum
  hosts: localhost
  gather_facts: false

  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "custom-cluster"

  tasks:

    - name: Fetch cluster details
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
      register: cluster_list_response

    - name: Fail if cluster not found
      fail:
        msg: "Cluster named {{ cluster_name }} not found!"
      when: cluster_list_response.json.data | length == 0

    - name: Set cluster ID
      set_fact:
        cluster_id: "{{ cluster_list_response.json.data[0].id }}"

    - name: Fetch registration tokens for this cluster
      uri:
        url: "{{ rancher_url }}/v3/clusterregistrationtokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
      register: tokens_response

    - name: Fail if no registration tokens found
      fail:
        msg: "No registration tokens found for cluster {{ cluster_name }}!"
      when: tokens_response.json.data | length == 0

    - name: Set token fact
      set_fact:
        token: "{{ tokens_response.json.data[0].token }}"

    - name: Try to get CA checksum from registration token
      set_fact:
        ca_checksum: >-
          {{ tokens_response.json.data[0].caChecksum
            | default(tokens_response.json.data[0]['ca-checksum']
            | default('')) }}
      ignore_errors: yes

    - name: Debug CA checksum from token
      debug:
        msg: "CA Checksum from token: {{ ca_checksum }}"

    - name: Get CA certs from Rancher settings if not found in token
      uri:
        url: "{{ rancher_url }}/v3/settings/cacerts"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
      register: ca_certs_response
      when: ca_checksum == ''
      ignore_errors: yes

    - name: Calculate CA checksum from PEM (if needed)
      shell: |
        echo "{{ ca_certs_response.json.value }}" | openssl x509 -noout -fingerprint -sha256 | cut -d'=' -f2 | tr -d ':' | tr 'A-Z' 'a-z'
      register: calculated_checksum
      when:
        - ca_checksum == ''
        - ca_certs_response is defined
        - ca_certs_response.json.value is defined
      ignore_errors: yes
      changed_when: false

    - name: Set CA checksum from calculated value
      set_fact:
        ca_checksum: "{{ calculated_checksum.stdout }}"
      when:
        - ca_checksum == ''
        - calculated_checksum is defined
        - calculated_checksum.stdout | length == 64

    - name: Get CA checksum from Rancher server cert as fallback
      shell: |
        openssl s_client -connect {{ rancher_url | regex_replace('^https://', '') }}:443 -showcerts </dev/null 2>/dev/null |
        openssl x509 -noout -fingerprint -sha256 | cut -d'=' -f2 | tr -d ':' | tr 'A-Z' 'a-z'
      register: openssl_ca_checksum
      when: ca_checksum == ''
      ignore_errors: yes
      changed_when: false

    - name: Set CA checksum from server certificate
      set_fact:
        ca_checksum: "{{ openssl_ca_checksum.stdout }}"
      when:
        - ca_checksum == ''
        - openssl_ca_checksum is defined
        - openssl_ca_checksum.stdout | length == 64

    - name: Final fallback – use empty CA checksum (insecure)
      set_fact:
        ca_checksum: ""
      when: ca_checksum == ''

    - name: Show final CA checksum
      debug:
        msg: "✅ Final CA Checksum used: {{ ca_checksum if ca_checksum else 'NONE (insecure mode)' }}"

    - name: Build final multi-line registration command
      set_fact:
        registration_cmd: >-
          curl --insecure -fL "{{ rancher_url }}/system-agent-install.sh" | sudo sh -s - 
          --server "{{ rancher_url }}" 
          --label 'cattle.io/os=linux' 
          --token "{{ token }}"
          {% if ca_checksum | length == 64 %} --ca-checksum "{{ ca_checksum }}" {% endif %}
          --etcd --controlplane --worker

    - name: Show registration command
      debug:
        msg: "{{ registration_cmd }}"

    - name: Build one-liner registration command
      set_fact:
        oneline_registration_cmd: >-
          curl --insecure -fL {{ rancher_url }}/system-agent-install.sh | sudo sh -s - --server {{ rancher_url }} --label 'cattle.io/os=linux' --token {{ token }} {% if ca_checksum | length == 64 %}--ca-checksum {{ ca_checksum }}{% endif %} --etcd --controlplane --worker

    - name: Show one-liner command
      debug:
        msg: "{{ oneline_registration_cmd }}"

    - name: Create local registration script
      copy:
        content: |
          #!/bin/bash
          {{ registration_cmd }}
        dest: "./register-{{ cluster_name }}.sh"
        mode: '0755'

    - name: Done – show summary
      debug:
        msg: |
          ✅ Registration command generated!

          📁 Script: ./register-{{ cluster_name }}.sh
          🔑 Token: {{ token }}
          🔐 CA Checksum: {{ ca_checksum if ca_checksum else 'Not used (insecure mode)' }}

          👉 Run this script on the node to register it!
