- name: Get Rancher cluster registration command
  hosts: localhost
  gather_facts: false
  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "openstack-cluster"

  tasks:
    - name: Fetch cluster details
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
      register: cluster_list_response

    - name: Fail if cluster not found
      fail:
        msg: "Cluster named {{ cluster_name }} not found!"
      when: cluster_list_response.json.data | length == 0

    - name: Set cluster ID
      set_fact:
        cluster_id: "{{ cluster_list_response.json.data[0].id }}"

    - name: Create cluster registration token
      uri:
        url: "{{ rancher_url }}/v3/clusterregistrationtokens"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
        validate_certs: false
        status_code: [200, 201]
      register: registration_response

    - name: Fetch registration tokens for this cluster
      uri:
        url: "{{ rancher_url }}/v3/clusterregistrationtokens?clusterId={{ cluster_id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
      register: tokens_response

    - name: Set token, command, and optional CA checksum
      set_fact:
        token: "{{ tokens_response.json.data[0].token }}"
        ca_checksum: "{{ tokens_response.json.data[0]['caChecksum'] | default('') }}"
        insecure_node_cmd: "{{ tokens_response.json.data[0].insecureNodeCommand }}"

    - name: Build exact registration command
      set_fact:
        registration_cmd: >-
          {{ insecure_node_cmd }}
          --server {{ rancher_url }}
          --label 'cattle.io/os=linux'
          --token {{ token }}
          --ca-checksum {{ ca_checksum }}
          --etcd --controlplane --worker

    - name: Print exact registration command
      debug:
        msg: "{{ registration_cmd }}"
