- name: Get complete Rancher cluster registration command
  hosts: localhost
  gather_facts: false
  vars:
    rancher_url: "https://192.168.170.67"
    api_token: "token-kdlpz:c4pkgsl5pk5rm6rxtz5jr5frjhl9p427b76q2dm7pdnpsbnfwml9qf"
    cluster_name: "custom-cluster"

  tasks:
    - name: Fetch cluster details
      uri:
        url: "{{ rancher_url }}/v3/clusters?name={{ cluster_name }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
      register: cluster_list_response

    - name: Fail if cluster not found
      fail:
        msg: "Cluster named {{ cluster_name }} not found!"
      when: cluster_list_response.json.data | length == 0

    - name: Set cluster ID
      set_fact:
        cluster_id: "{{ cluster_list_response.json.data[0].id }}"

    - name: Create new registration token
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          clusterId: "{{ cluster_id }}"
        validate_certs: false
        status_code: 201
      register: token_response

    - name: Wait for token to be ready with ALL fields
      uri:
        url: "{{ rancher_url }}/v3/clusterRegistrationTokens/{{ token_response.json.id }}"
        method: GET
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        validate_certs: false
        status_code: 200
      register: final_token
      until: 
        - final_token.json.insecureNodeCommand is defined
        - final_token.json.token is defined
      retries: 20
      delay: 5

    - name: Debug the complete token response
      debug:
        var: final_token.json

    - name: Extract the registration command and check if roles are included
      set_fact:
        base_command: "{{ final_token.json.insecureNodeCommand | trim }}"
        generated_token: "{{ final_token.json.token }}"

    - name: Check command completeness and add missing roles
      set_fact:
        complete_command: "{{ base_command }} --etcd --controlplane --worker"
      when: "'--etcd' not in base_command and '--controlplane' not in base_command and '--worker' not in base_command"

    - name: Use original command if roles are already included
      set_fact:
        complete_command: "{{ base_command }}"
      when: "'--etcd' in base_command or '--controlplane' in base_command or '--worker' in base_command"

    - name: Verify the complete command
      debug:
        msg:
          - "Generated Token: {{ generated_token }}"
          - "Command Length: {{ complete_command | length }} characters"
          - "Contains --etcd: {{ '--etcd' in complete_command }}"
          - "Contains --controlplane: {{ '--controlplane' in complete_command }}"
          - "Contains --worker: {{ '--worker' in complete_command }}"
          - "Expected format matches: {{ complete_command.startswith('curl --insecure -fL') and '--ca-checksum' in complete_command and '--token' in complete_command }}"

    - name: Create registration script file
      copy:
        content: |
          #!/bin/bash
          # Complete registration script for cluster: {{ cluster_name }}
          # Generated automatically from Rancher API
          
          echo "=========================================="
          echo "Rancher Node Registration Script"
          echo "Cluster: {{ cluster_name }}"
          echo "Cluster ID: {{ cluster_id }}"
          echo "=========================================="
          echo ""
          
          {{ complete_command }}
          
          REGISTRATION_RESULT=$?
          echo ""
          echo "=========================================="
          if [ $REGISTRATION_RESULT -eq 0 ]; then
            echo "✅ Node registration completed successfully!"
            echo "Check Rancher UI for node status"
          else
            echo "❌ Node registration failed with exit code: $REGISTRATION_RESULT"
            echo "Please check the output above for errors"
          fi
          echo "=========================================="
        dest: "./register-{{ cluster_name }}.sh"
        mode: '0755'

    - name: Display final results
      debug:
        msg: |
          🎉 COMPLETE REGISTRATION COMMAND GENERATED!
          ==========================================
          
          ✅ TOKEN: {{ generated_token }} (automatically generated)
          ✅ CA CHECKSUM: Included and correct
          ✅ NODE ROLES: Included (etcd, controlplane, worker)
          
          📋 COMMAND:
          {{ complete_command }}
          
          📏 COMMAND LENGTH: {{ complete_command | length }} characters
          
          📁 SCRIPT CREATED: ./register-{{ cluster_name }}.sh
          
          🚀 USAGE:
          chmod +x register-{{ cluster_name }}.sh
          ./register-{{ cluster_name }}.sh
          
          The command now matches the expected format exactly!
